---WARNING this file was generated by premake-manager-cli!!!
---change at your own risk!
premake.path = premake.path..";"..path.join(_MAIN_SCRIPT_DIR, "modules")
premake.path = premake.path..";"..path.join(_MAIN_SCRIPT_DIR, "libraries")